language: android
android:
  components:
    - platform-tools
    - build-tools-23.0.3
    - android-23
    - extra-google-google_play_services
before_install: 
 - cd GestioneOrario
 - chmod +x gradlew
script: ./gradlew build 
